"""Initial migration

Revision ID: 5193efdcc309
Revises: 
Create Date: 2026-05-27 00:28:03.572688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = '5193efdcc309'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operadores',
    sa.Column('id', oracle.NUMBER(asdecimal=False), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'ATIVO'"), nullable=False),
    sa.Column('dt_cadastro', sa.DateTime(), server_default=sa.text('SYSDATE'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('produtos',
    sa.Column('id', oracle.NUMBER(asdecimal=False), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('unidade', sa.String(length=10), server_default=sa.text("'UN'"), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.String(length=1), server_default=sa.text("'S'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('setores',
    sa.Column('id', oracle.NUMBER(asdecimal=False), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('enderecos',
    sa.Column('id', oracle.NUMBER(asdecimal=False), autoincrement=True, nullable=False),
    sa.Column('rua', sa.String(length=5), nullable=False),
    sa.Column('coluna', sa.String(length=5), nullable=False),
    sa.Column('nivel', sa.String(length=5), nullable=False),
    sa.Column('apartamento', sa.String(length=5), nullable=False),
    sa.Column('codigo_verificacao', sa.String(length=10), nullable=False),
    sa.Column('setor_id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'ATIVO'"), nullable=False),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordens',
    sa.Column('id', oracle.NUMBER(asdecimal=False), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('operador_id', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'AGUARDANDO'"), nullable=False),
    sa.Column('prioridade', sa.String(length=10), server_default=sa.text("'NORMAL'"), nullable=False),
    sa.Column('dt_criacao', sa.DateTime(), server_default=sa.text('SYSDATE'), nullable=False),
    sa.Column('dt_inicio', sa.DateTime(), nullable=True),
    sa.Column('dt_conclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operador_id'], ['operadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('estoque',
    sa.Column('id', oracle.NUMBER(asdecimal=False), autoincrement=True, nullable=False),
    sa.Column('produto_id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('endereco_id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('quantidade', oracle.NUMBER(asdecimal=False), server_default=sa.text('0'), nullable=False),
    sa.Column('dt_atualizacao', sa.DateTime(), server_default=sa.text('SYSDATE'), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_ordem',
    sa.Column('id', oracle.NUMBER(asdecimal=False), autoincrement=True, nullable=False),
    sa.Column('ordem_id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('produto_id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('endereco_id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('sequencia', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('qtd_solicitada', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('qtd_coletada', oracle.NUMBER(asdecimal=False), server_default=sa.text('0'), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'PENDENTE'"), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_coleta',
    sa.Column('id', oracle.NUMBER(asdecimal=False), autoincrement=True, nullable=False),
    sa.Column('item_id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('operador_id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('codigo_informado', sa.String(length=10), nullable=False),
    sa.Column('sucesso', sa.String(length=1), nullable=False),
    sa.Column('tentativa', oracle.NUMBER(asdecimal=False), server_default=sa.text('1'), nullable=False),
    sa.Column('dt_registro', sa.DateTime(), server_default=sa.text('SYSDATE'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['itens_ordem.id'], ),
    sa.ForeignKeyConstraint(['operador_id'], ['operadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_coleta')
    op.drop_table('itens_ordem')
    op.drop_table('estoque')
    op.drop_table('ordens')
    op.drop_table('enderecos')
    op.drop_table('setores')
    op.drop_table('produtos')
    op.drop_table('operadores')
    # ### end Alembic commands ###
